import { Deal, Merchant, AdBanner, DealCategory, SmartEssential } from '../types/deals';

export const topAdBanners: AdBanner[] = [
  {
    id: 'ad1',
    title: 'Promote Your Business',
    subtitle: 'Reach local customers with smart, targeted deals.',
    ctaLabel: 'List your deals',
    onClickTarget: '/merchant',
    gradientFrom: 'from-blue-500',
    gradientTo: 'to-cyan-500',
  },
  {
    id: 'ad2',
    title: 'Classifieds Buddy is Live',
    subtitle: 'Post jobs, rentals, and services in your community.',
    ctaLabel: 'Explore classifieds',
    onClickTarget: '/classifieds',
    gradientFrom: 'from-purple-500',
    gradientTo: 'to-pink-500',
  },
];

export const dealCategories: DealCategory[] = [
  { id: 'all', name: 'All Deals', icon: '🎯', slug: 'all' },
  { id: 'food', name: 'Food & Dining', icon: '🍕', slug: 'food' },
  { id: 'grocery', name: 'Groceries', icon: '🛒', slug: 'grocery' },
  { id: 'health', name: 'Health & Beauty', icon: '💅', slug: 'health' },
  { id: 'auto', name: 'Auto Services', icon: '🚗', slug: 'auto' },
  { id: 'home', name: 'Home & Garden', icon: '🏡', slug: 'home' },
  { id: 'entertainment', name: 'Entertainment', icon: '🎬', slug: 'entertainment' },
  { id: 'retail', name: 'Retail', icon: '🛍️', slug: 'retail' },
];

export const mockDeals: Deal[] = [
  {
    id: 'd1',
    merchantId: 'm1',
    merchantName: 'Pizza Palace',
    merchantLogo: 'https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: '50% Off Family Pizza Combo',
    description: 'Get 2 large pizzas, breadsticks, and a 2-liter soda for half price!',
    originalPrice: 45.99,
    discountedPrice: 22.99,
    discountPercentage: 50,
    category: 'food',
    imageUrl: 'https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Downtown',
    distance: 0.8,
    expiresAt: '2025-12-31T23:59:59Z',
    isSponsored: true,
    isFeatured: true,
    tags: ['Family Deal', 'Popular'],
    redeemInstructions: 'Show this deal at checkout or mention code: PIZZA50',
  },
  {
    id: 'd2',
    merchantId: 'm2',
    merchantName: 'Fresh Mart Grocery',
    merchantLogo: 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: '$20 Off Your $100+ Purchase',
    description: 'Save big on your weekly grocery shopping. Fresh produce, organic options, and more!',
    originalPrice: 100,
    discountedPrice: 80,
    discountPercentage: 20,
    category: 'grocery',
    imageUrl: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'West Side',
    distance: 1.2,
    expiresAt: '2025-12-20T23:59:59Z',
    isFeatured: true,
    tags: ['Grocery', 'Savings'],
    redeemInstructions: 'Present this coupon at checkout. Valid on orders $100+',
  },
  {
    id: 'd3',
    merchantId: 'm3',
    merchantName: 'Glow Spa & Salon',
    merchantLogo: 'https://images.pexels.com/photos/3738386/pexels-photo-3738386.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: '40% Off All Hair Services',
    description: 'Haircut, color, styling and more. Book your appointment today!',
    originalPrice: 75,
    discountedPrice: 45,
    discountPercentage: 40,
    category: 'health',
    imageUrl: 'https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Uptown',
    distance: 2.1,
    expiresAt: '2025-12-25T23:59:59Z',
    tags: ['Beauty', 'New Customer'],
    redeemInstructions: 'Call to book and mention this deal',
  },
  {
    id: 'd4',
    merchantId: 'm4',
    merchantName: 'AutoCare Express',
    merchantLogo: 'https://images.pexels.com/photos/13065690/pexels-photo-13065690.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: '$15 Full Service Oil Change',
    description: 'Keep your car running smooth with our professional oil change service.',
    originalPrice: 39.99,
    discountedPrice: 15,
    discountPercentage: 62,
    category: 'auto',
    imageUrl: 'https://images.pexels.com/photos/13065690/pexels-photo-13065690.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'East Bay',
    distance: 3.5,
    expiresAt: '2025-12-28T23:59:59Z',
    isSponsored: true,
    tags: ['Auto', 'Maintenance'],
    redeemInstructions: 'Schedule online or walk-in with this coupon',
  },
  {
    id: 'd5',
    merchantId: 'm5',
    merchantName: 'Home Depot',
    merchantLogo: 'https://images.pexels.com/photos/5691622/pexels-photo-5691622.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: '30% Off Paint & Supplies',
    description: 'Transform your space! Premium paint brands and all painting supplies included.',
    originalPrice: 150,
    discountedPrice: 105,
    discountPercentage: 30,
    category: 'home',
    imageUrl: 'https://images.pexels.com/photos/1669754/pexels-photo-1669754.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'South Plaza',
    distance: 4.2,
    expiresAt: '2025-12-30T23:59:59Z',
    tags: ['DIY', 'Home Improvement'],
    redeemInstructions: 'Present in-store or use code PAINT30 online',
  },
  {
    id: 'd6',
    merchantId: 'm6',
    merchantName: 'Cinema Plus',
    merchantLogo: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: 'Buy 1 Get 1 Free Movie Tickets',
    description: 'Enjoy the latest blockbusters! Valid for all showtimes.',
    originalPrice: 28,
    discountedPrice: 14,
    discountPercentage: 50,
    category: 'entertainment',
    imageUrl: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'City Center',
    distance: 1.8,
    expiresAt: '2025-12-24T23:59:59Z',
    tags: ['Entertainment', 'Movies'],
    redeemInstructions: 'Purchase at box office with this coupon',
  },
  {
    id: 'd7',
    merchantId: 'm7',
    merchantName: "Joe's Coffee House",
    merchantLogo: 'https://images.pexels.com/photos/2074130/pexels-photo-2074130.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: 'Free Pastry with Any Coffee',
    description: 'Start your morning right! Choose from our fresh daily selection.',
    originalPrice: 8.5,
    discountedPrice: 4.5,
    discountPercentage: 47,
    category: 'food',
    imageUrl: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Downtown',
    distance: 0.5,
    expiresAt: '2025-12-22T23:59:59Z',
    tags: ['Coffee', 'Breakfast'],
    redeemInstructions: 'Valid 6am-11am daily. Show at register.',
  },
  {
    id: 'd8',
    merchantId: 'm8',
    merchantName: 'FitLife Gym',
    merchantLogo: 'https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: 'First Month Free + Personal Training',
    description: 'New members only. Includes 3 free personal training sessions!',
    originalPrice: 89,
    discountedPrice: 0,
    discountPercentage: 100,
    category: 'health',
    imageUrl: 'https://images.pexels.com/photos/1954524/pexels-photo-1954524.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'North District',
    distance: 2.7,
    expiresAt: '2025-12-29T23:59:59Z',
    isFeatured: true,
    tags: ['Fitness', 'New Member'],
    redeemInstructions: 'Visit in person to sign up. Valid ID required.',
  },
  {
    id: 'd9',
    merchantId: 'm9',
    merchantName: 'Fashion Outlet',
    merchantLogo: 'https://images.pexels.com/photos/1884581/pexels-photo-1884581.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: '25% Off Entire Store',
    description: 'End of season clearance! Clothing, shoes, and accessories.',
    originalPrice: 200,
    discountedPrice: 150,
    discountPercentage: 25,
    category: 'retail',
    imageUrl: 'https://images.pexels.com/photos/1884581/pexels-photo-1884581.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Mall Plaza',
    distance: 3.8,
    expiresAt: '2025-12-26T23:59:59Z',
    tags: ['Fashion', 'Clearance'],
    redeemInstructions: 'Show coupon at checkout. Cannot combine with other offers.',
  },
  {
    id: 'd10',
    merchantId: 'm10',
    merchantName: 'Green Leaf Restaurant',
    merchantLogo: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: '35% Off Dinner for Two',
    description: 'Farm-to-table dining experience. Vegan and vegetarian options available.',
    originalPrice: 65,
    discountedPrice: 42.25,
    discountPercentage: 35,
    category: 'food',
    imageUrl: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Downtown',
    distance: 1.1,
    expiresAt: '2025-12-27T23:59:59Z',
    tags: ['Dining', 'Healthy'],
    redeemInstructions: 'Reservations recommended. Mention deal when booking.',
  },
  {
    id: 'd11',
    merchantId: 'm11',
    merchantName: 'Tech Repair Pro',
    merchantLogo: 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: '50% Off Phone Screen Repair',
    description: 'Fast, professional repairs. Most devices fixed in under an hour.',
    originalPrice: 120,
    discountedPrice: 60,
    discountPercentage: 50,
    category: 'retail',
    imageUrl: 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'Tech District',
    distance: 2.5,
    expiresAt: '2025-12-31T23:59:59Z',
    tags: ['Technology', 'Repair'],
    redeemInstructions: 'Walk-in or schedule online. Bring this coupon.',
  },
  {
    id: 'd12',
    merchantId: 'm12',
    merchantName: 'Pet Paradise',
    merchantLogo: 'https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg?auto=compress&cs=tinysrgb&w=100',
    title: 'Free Grooming with Daycare',
    description: 'Your pet deserves the best! Professional grooming included with full day.',
    originalPrice: 75,
    discountedPrice: 45,
    discountPercentage: 40,
    category: 'retail',
    imageUrl: 'https://images.pexels.com/photos/1254140/pexels-photo-1254140.jpeg?auto=compress&cs=tinysrgb&w=800',
    location: 'West End',
    distance: 3.2,
    expiresAt: '2025-12-23T23:59:59Z',
    tags: ['Pets', 'Grooming'],
    redeemInstructions: 'Book online or call ahead. New customers only.',
  },
];

export const mockMerchants: Merchant[] = [
  {
    id: 'm1',
    name: 'Pizza Palace',
    logo: 'https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=100',
    description: 'Best pizza in town! Family-owned since 1995.',
    category: 'Food & Dining',
    location: 'Downtown',
    distance: 0.8,
    rating: 4.7,
    reviewCount: 342,
    activeDealsCount: 3,
    isVerified: true,
    coverImage: 'https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'm2',
    name: 'Fresh Mart Grocery',
    logo: 'https://images.pexels.com/photos/264636/pexels-photo-264636.jpeg?auto=compress&cs=tinysrgb&w=100',
    description: 'Your neighborhood grocery store with fresh local produce.',
    category: 'Groceries',
    location: 'West Side',
    distance: 1.2,
    rating: 4.5,
    reviewCount: 856,
    activeDealsCount: 5,
    isVerified: true,
    coverImage: 'https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'm3',
    name: 'Glow Spa & Salon',
    logo: 'https://images.pexels.com/photos/3738386/pexels-photo-3738386.jpeg?auto=compress&cs=tinysrgb&w=100',
    description: 'Luxury spa services and professional hair care.',
    category: 'Health & Beauty',
    location: 'Uptown',
    distance: 2.1,
    rating: 4.9,
    reviewCount: 234,
    activeDealsCount: 4,
    isVerified: true,
    coverImage: 'https://images.pexels.com/photos/3993449/pexels-photo-3993449.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
  {
    id: 'm4',
    name: 'AutoCare Express',
    logo: 'https://images.pexels.com/photos/13065690/pexels-photo-13065690.jpeg?auto=compress&cs=tinysrgb&w=100',
    description: 'Fast, reliable auto maintenance and repair.',
    category: 'Auto Services',
    location: 'East Bay',
    distance: 3.5,
    rating: 4.6,
    reviewCount: 567,
    activeDealsCount: 2,
    isVerified: true,
    coverImage: 'https://images.pexels.com/photos/13065690/pexels-photo-13065690.jpeg?auto=compress&cs=tinysrgb&w=800',
  },
];

export const smartEssentials: SmartEssential[] = [
  {
    id: 'se1',
    title: 'Quick Bites',
    subtitle: 'Food deals under 1 mile',
    icon: '🍔',
    deals: mockDeals.filter(d => d.category === 'food' && d.distance < 1.5),
  },
  {
    id: 'se2',
    title: 'Weekly Grocery',
    subtitle: 'Save on groceries nearby',
    icon: '🛒',
    deals: mockDeals.filter(d => d.category === 'grocery'),
  },
  {
    id: 'se3',
    title: 'Self Care',
    subtitle: 'Health & beauty deals',
    icon: '💆',
    deals: mockDeals.filter(d => d.category === 'health'),
  },
];

// Mock inline ad data (shown every 10 deals)
export const inlineAds: AdBanner[] = [
  {
    id: 'inline1',
    title: 'List Your Business',
    subtitle: 'Reach 10,000+ local customers',
    ctaLabel: 'Get started',
    onClickTarget: '/merchant',
    gradientFrom: 'from-green-500',
    gradientTo: 'to-teal-500',
  },
  {
    id: 'inline2',
    title: 'Travel Companion',
    subtitle: 'Find travel buddies nearby',
    ctaLabel: 'Explore now',
    onClickTarget: '/travel',
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-red-500',
  },
];
