export const ADSENSE_CLIENT = "ca-pub-XXXXXXXXXXXX";

export const ADSENSE_SLOTS = {
  LIST_TOP: "LIST_TOP_SLOT_ID",
  LIST_INLINE: "LIST_INLINE_SLOT_ID",
  LIST_SIDEBAR: "LIST_SIDEBAR_SLOT_ID",
  DETAIL_TOP: "DETAIL_TOP_SLOT_ID",
  DETAIL_IN_ARTICLE: "DETAIL_IN_ARTICLE_SLOT_ID",
  DETAIL_BOTTOM: "DETAIL_BOTTOM_SLOT_ID",
  COUPON_SIDEBAR_1: "COUPON_SIDEBAR_1_SLOT_ID",
  COUPON_SIDEBAR_2: "COUPON_SIDEBAR_2_SLOT_ID",
  COUPON_SIDEBAR_3: "COUPON_SIDEBAR_3_SLOT_ID",
};
